import type { AdminReservation } from "./types";

export const mockAdminReservations: AdminReservation[] = [
  {
    id: 1,
    status: "pending",
    kind: "single",
    dateLabel: "05.08 (금)",
    dayOffset: 1,
    timeLabel: "19:00~21:00",
    room: "B201",
    teamId: 1,
    teamName: "A팀",
    reserverUserId: 1,
    reserverName: "김민준",
  },
  {
    id: 2,
    status: "pending",
    kind: "repeat",
    dateLabel: "매주 화/목",
    dayOffset: 4,
    timeLabel: "18:00~20:00",
    periodLabel: "05.12~06.30",
    room: "B203",
    teamId: 2,
    teamName: "B팀",
    reserverUserId: 2,
    reserverName: "서연우",
  },
  {
    id: 3,
    status: "pending",
    kind: "single",
    dateLabel: "05.09 (토)",
    dayOffset: 2,
    timeLabel: "14:00~16:00",
    room: "B201",
    reserverUserId: 3,
    reserverName: "박지훈",
  },
  {
    id: 4,
    status: "pending",
    kind: "repeat",
    dateLabel: "매주 수",
    dayOffset: 8,
    timeLabel: "20:00~22:00",
    periodLabel: "05.14~07.02",
    room: "B203",
    teamId: 3,
    teamName: "C팀",
    reserverUserId: 7,
    reserverName: "최유진",
  },
  {
    id: 5,
    status: "approved",
    kind: "single",
    dateLabel: "05.10 (일)",
    dayOffset: 3,
    timeLabel: "17:00~19:00",
    room: "B201",
    teamId: 4,
    teamName: "D팀",
    reserverUserId: 6,
    reserverName: "정하린",
  },
  {
    id: 6,
    status: "approved",
    kind: "repeat",
    dateLabel: "매주 금",
    dayOffset: 9,
    timeLabel: "19:00~21:00",
    periodLabel: "05.16~06.27",
    room: "B203",
    teamId: 2,
    teamName: "B팀",
    reserverUserId: 2,
    reserverName: "서연우",
  },
  {
    id: 7,
    status: "approved",
    kind: "single",
    dateLabel: "05.11 (월)",
    dayOffset: 14,
    timeLabel: "15:00~17:00",
    room: "B201",
    reserverUserId: 4,
    reserverName: "이수빈",
  },
];
