# Generated by Django 6.0.3 on 2026-04-09 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("studios", "0001_initial"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "reservation_number",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[("PRIVATE", "PRIVATE"), ("TEAM", "TEAM")],
                        max_length=20,
                    ),
                ),
                ("reservation_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RESERVED", "RESERVED"),
                            ("CANCELED", "CANCELED"),
                            ("PENDING", "PENDING"),
                        ],
                        default="RESERVED",
                        max_length=20,
                    ),
                ),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="studios.studioroom",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reservations",
                "ordering": ["reservation_date", "start_time", "reservation_number"],
                "indexes": [
                    models.Index(
                        fields=["room", "reservation_date", "status"],
                        name="reservation_room_id_a394e7_idx",
                    ),
                    models.Index(
                        fields=["room", "reservation_date", "start_time", "end_time"],
                        name="reservation_room_id_0d6d57_idx",
                    ),
                    models.Index(
                        fields=["user", "status", "reservation_date"],
                        name="reservation_user_id_2fba55_idx",
                    ),
                    models.Index(
                        fields=["team", "status", "reservation_date"],
                        name="reservation_team_id_074a6e_idx",
                    ),
                    models.Index(
                        fields=["reservation_date", "status"],
                        name="reservation_reserva_da5cf8_idx",
                    ),
                ],
            },
        ),
    ]
