# Generated by Django 6.0.3 on 2026-05-22 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_booking_repeat_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="booking",
            new_name="reservation_repeat__7497e3_idx",
            old_name="reservatio_repeat__0476a7_idx",
        ),
    ]
