# Generated by Django 6.0.3 on 2026-04-09 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudioRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rooms",
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "sort_order"], name="rooms_status_96ad51_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoomClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("closure_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "closure_type",
                    models.CharField(
                        choices=[
                            ("BLOCKED", "BLOCKED"),
                            ("HOLIDAY", "HOLIDAY"),
                            ("MAINTENANCE", "MAINTENANCE"),
                        ],
                        default="BLOCKED",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closures",
                        to="studios.studioroom",
                    ),
                ),
            ],
            options={
                "db_table": "room_closures",
                "indexes": [
                    models.Index(
                        fields=["room", "closure_date"],
                        name="room_closur_room_id_1a8246_idx",
                    ),
                    models.Index(
                        fields=["room", "closure_date", "start_time", "end_time"],
                        name="room_closur_room_id_c5fb07_idx",
                    ),
                ],
            },
        ),
    ]
