# Generated by Django 6.0.3 on 2026-05-22 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studios", "0004_roomclosure_admin_day_off_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="roomclosure",
            new_name="room_closur_room_id_75d42a_idx",
            old_name="room_closur_room_id_e6c6b5_idx",
        ),
    ]
