# Generated by Django 6.0.3 on 2026-05-22 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="adminactionlog",
            new_name="admin_actio_created_9b91e7_idx",
            old_name="admin_actio_created_c9a2af_idx",
        ),
        migrations.RenameIndex(
            model_name="adminactionlog",
            new_name="admin_actio_categor_04f52e_idx",
            old_name="admin_actio_categor_843a8f_idx",
        ),
    ]
