# Generated by Django 6.0.3 on 2026-05-11 18:43

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_TEAM_COLORS = [
    "FF6A2A",
    "FF3B3B",
    "FFD60A",
    "A7F432",
    "06D6A0",
    "00E5FF",
    "4CC9F0",
    "4361EE",
    "3A0CA3",
    "7209B7",
    "B5179E",
    "F72585",
    "F9844A",
    "90BE6D",
    "577590",
    "E76F51",
]


def seed_and_assign_team_colors(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    TeamColor = apps.get_model("teams", "TeamColor")

    for index, color in enumerate(DEFAULT_TEAM_COLORS):
        TeamColor.objects.get_or_create(
            color=color,
            defaults={"display_order": index, "is_active": True},
        )

    for team in Team.objects.exclude(color__isnull=True).exclude(color="").order_by(
        "id"
    ):
        color = team.color.strip().lstrip("#").upper()
        team_color, created = TeamColor.objects.get_or_create(
            color=color,
            defaults={
                "display_order": len(DEFAULT_TEAM_COLORS),
                "is_active": True,
            },
        )
        if team_color.team_id is None:
            team_color.team_id = team.id
            team_color.save(update_fields=["team"])


def restore_team_color_values(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    TeamColor = apps.get_model("teams", "TeamColor")

    for team_color in TeamColor.objects.exclude(team__isnull=True):
        Team.objects.filter(id=team_color.team_id).update(color=team_color.color)


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=6, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "team",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_color",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_colors",
            },
        ),
        migrations.AddIndex(
            model_name="teamcolor",
            index=models.Index(fields=["team"], name="team_colors_team_id_56a0d6_idx"),
        ),
        migrations.AddIndex(
            model_name="teamcolor",
            index=models.Index(
                fields=["is_active", "display_order"],
                name="team_colors_is_acti_deb610_idx",
            ),
        ),
        migrations.RunPython(seed_and_assign_team_colors, restore_team_color_values),
        migrations.RemoveField(
            model_name="team",
            name="color",
        ),
    ]
