name: FE CI

on:
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "FE/**"
      - ".github/workflows/fe_ci.yaml"
  push:
    branches: ["main", "dev"]
    paths:
      - "FE/**"
      - ".github/workflows/fe_ci.yaml"

jobs:
  fe-ci:
    name: React CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: FE

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: FE/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

